const { withMainActivity } = require('@expo/config-plugins');

/** @type {import('expo/config').ExpoConfig} */
const config = require('./app.json').expo;

// Back-press on the root screen should send the app to the background, not finish the
// Activity. The SDK 54 template only does that on Android R and below; on S+ it falls
// through to the default, which destroys the Activity. Two problems with that:
//
//   1. Destroying the Activity tears down the socket mid-shift — a driver who taps back
//      while online silently stops receiving trip.request events.
//   2. The dev client keeps the JS runtime alive across the destroy, so React never runs
//      effect cleanups. Clerk's ClerkProvider guard keeps a module-level mount counter
//      that only decrements in cleanup, so it never resets and reopening the app throws
//      "You've added multiple <ClerkProvider> components".
//
// android/ is gitignored (generated by prebuild), so this lives here to survive
// `expo prebuild` and to reach EAS builds.
const BACK_PRESSED_METHOD = `override fun invokeDefaultOnBackPressed() {
      // Root activities move to the background instead of being finished. See the note
      // in app.config.js — destroying the Activity drops the driver socket.
      if (!moveTaskToBack(false)) {
          // For non-root activities, use the default implementation to finish them.
          super.invokeDefaultOnBackPressed()
      }
  }`;

/**
 * Replaces the body of `invokeDefaultOnBackPressed` in the generated MainActivity.
 * Throws rather than no-oping if the template shape changes, so an Expo upgrade fails
 * the build loudly instead of silently reverting the behaviour.
 */
function withRootBackPressBackgrounds(expoConfig) {
  return withMainActivity(expoConfig, (cfg) => {
    if (cfg.modResults.language !== 'kt') {
      throw new Error(
        `[teeko] MainActivity is ${cfg.modResults.language}, expected kt. Update the back-press plugin in app.config.js.`
      );
    }

    const contents = cfg.modResults.contents;
    const start = contents.indexOf('override fun invokeDefaultOnBackPressed()');
    if (start === -1) {
      throw new Error(
        '[teeko] Could not find invokeDefaultOnBackPressed in MainActivity. Update the back-press plugin in app.config.js.'
      );
    }

    // Walk braces to find the end of the method rather than pattern-matching the
    // template body, which changes between SDK versions.
    const open = contents.indexOf('{', start);
    let depth = 0;
    let end = -1;
    for (let i = open; i < contents.length; i++) {
      if (contents[i] === '{') depth++;
      else if (contents[i] === '}') {
        depth--;
        if (depth === 0) {
          end = i + 1;
          break;
        }
      }
    }
    if (end === -1) {
      throw new Error(
        '[teeko] Unbalanced braces in MainActivity.invokeDefaultOnBackPressed. Update the back-press plugin in app.config.js.'
      );
    }

    let patched = contents.slice(0, start) + BACK_PRESSED_METHOD + contents.slice(end);

    // The android.os.Build import is only used by the template's SDK check, which we
    // just removed. Drop it so the file compiles without an unused-import warning.
    patched = patched.replace(/^import android\.os\.Build\r?\n/m, '');

    cfg.modResults.contents = patched;
    return cfg;
  });
}

module.exports = {
  expo: withRootBackPressBackgrounds({
    ...config,
    android: {
      ...config.android,
      config: {
        googleMaps: {
          apiKey: process.env.GOOGLE_MAPS_API_KEY,
        },
      },
    },
  }),
};
