// scripts/generate-countries.ts
//
// Emits `src/data/countries.ts` — the checked-in country dataset the rider's
// phone picker renders and `utils/phone.ts` validates against.
//
// libphonenumber-js is a **devDependency**: its ~145KB of metadata must never
// reach the Expo bundles, so we distil it here into a plain array and commit
// the result. Re-run with `pnpm --filter @teeko/shared gen:countries` after a
// libphonenumber-js bump; the diff is the review.
//
// Per-country `lengths` are probed through the public
// `validatePhoneNumberLength` API rather than read out of metadata.min.json by
// array index — the internal layout is not a contract, the probe is.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  getCountries,
  getCountryCallingCode,
  getExampleNumber,
  validatePhoneNumberLength,
  type CountryCode,
} from 'libphonenumber-js';
import examples from 'libphonenumber-js/mobile/examples';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/countries.ts');

/** 🇲🇾 from 'MY' — two regional-indicator code points, offset from 'A'. */
function flagOf(iso2: string): string {
  return String.fromCodePoint(
    ...[...iso2.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65),
  );
}

const displayNames = new Intl.DisplayNames(['en'], { type: 'region' });

function nameOf(iso2: string): string {
  try {
    return displayNames.of(iso2) ?? iso2;
  } catch {
    return iso2;
  }
}

/**
 * Every national-number length the country accepts.
 *
 * Probed by feeding `validatePhoneNumberLength` a synthetic number of each
 * length, built by cycling the country's own example number so the leading
 * digits stay plausible — a run of `1`s trips the pattern check in some
 * countries and would under-report the valid lengths.
 */
function lengthsOf(country: CountryCode, example: string): number[] {
  const seed = example || '1';
  const found: number[] = [];
  for (let n = 1; n <= 15; n++) {
    const digits = Array.from({ length: n }, (_, i) => seed[i % seed.length]).join('');
    if (validatePhoneNumberLength(digits, country) === undefined) found.push(n);
  }
  return found;
}

const rows = getCountries()
  .map((iso2) => {
    const dialCode = getCountryCallingCode(iso2);
    const example = getExampleNumber(iso2, examples)?.nationalNumber ?? '';
    return {
      iso2,
      name: nameOf(iso2),
      dialCode,
      flag: flagOf(iso2),
      example,
      lengths: lengthsOf(iso2, example),
    };
  })
  // A country we cannot length-check would accept anything; surface it at
  // generation time rather than shipping a hole in the validator.
  .filter((r) => {
    if (r.lengths.length) return true;
    console.warn(`skipping ${r.iso2}: no probeable lengths`);
    return false;
  })
  .sort((a, b) => a.name.localeCompare(b.name, 'en'));

const body = rows
  .map(
    (r) =>
      `  { iso2: '${r.iso2}', name: ${JSON.stringify(r.name)}, dialCode: '${r.dialCode}', ` +
      `flag: '${r.flag}', example: '${r.example}', lengths: [${r.lengths.join(', ')}] },`,
  )
  .join('\n');

const file = `// AUTO-GENERATED by scripts/generate-countries.ts — do not edit by hand.
// Regenerate with: pnpm --filter @teeko/shared gen:countries
// Source: libphonenumber-js (devDependency; deliberately not bundled at runtime).

export type Country = {
  /** ISO-3166 alpha-2, the value stored in \`users.phone_country\`. */
  iso2: string;
  /** English display name; the picker's search matches on this and on dialCode. */
  name: string;
  /** Calling code without the leading '+'. Not unique — +1 covers US, CA and more. */
  dialCode: string;
  flag: string;
  /** A real national number, shown as the input's placeholder. */
  example: string;
  /** Every national-number length this country accepts. */
  lengths: number[];
};

export const COUNTRIES: readonly Country[] = [
${body}
];

/** Lookup by ISO-3166 alpha-2. */
export const COUNTRY_BY_ISO2: Readonly<Record<string, Country>> = Object.fromEntries(
  COUNTRIES.map((c) => [c.iso2, c]),
);
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, file, 'utf8');
console.log(`wrote ${rows.length} countries to ${OUT}`);
